### ISSUE TITLE
Request only accepts http.

### ISSUE THREAD

**Issue by alangregory** [FaCuZ/zabbix-rpc#11]
Hi, some server are using https, there should be an option to specify the protocol.
https://github.com/FaCuZ/zabbix-rpc/blob/3ca9fd7a20173be017f27bfd783221a8362947c1/lib/Request.js#L28

**Comment by Troctor** [comment]
[zabbix-rpc-1.2.3.zip](https://github.com/FaCuZ/zabbix-rpc/files/10395742/zabbix-rpc-1.2.3.zip)
for those running into this, i made a patched package you can link locally.

**Comment by FaCuZ** [comment]
Thanks for the help. With the new version 1.2.4 it can be included in the protocol in the host (without breaking backwards compatibility)

For example
`const z = new Zabbix('https://example.com/zabbix')`
`const z = new Zabbix('http://example.com/zabbix')`
`const z = new Zabbix('example.com/zabbix') // http://`

Commit: [4afd4be](https://github.com/FaCuZ/zabbix-rpc/commit/4afd4befd05c6d25f293ea2dbe610b65b3419843)
